### ISSUE TITLE
Make YAML Configuration and Rails Config Equivalent

### ISSUE THREAD

**Issue by allcentury** [basecamp/solid_queue#102]
For `matt_accessor`'s that [are settable](https://github.com/basecamp/solid_queue/blob/main/lib/solid_queue.rb#L26-L43), I am unable to set some of these in `config.yml`. 

For example, `silence_polling` in development:

```yaml
development:
  <<: *default
  silence_polling: true
```

I'm unable to find the exact problem but happy to put in a fix if someone can point me in the right direction.  Maybe [here](https://github.com/basecamp/solid_queue/blob/main/lib/solid_queue/engine.rb#L15), but I don't see how is this line called?

**Comment by rosa** [comment]
Hey @allcentury, sorry for the confusion! All the settings in [this section](https://github.com/basecamp/solid_queue?tab=readme-ov-file#other-configuration-settings) can be set in your `config/application.rb` file or in your environment specific file (such as `development.rb`), or in an initializer for Solid Queue alone. For example, in your `application.rb` file, you'd include something like: 
```ruby
config.solid_queue.silence_polling = true
```

**Comment by allcentury** [comment]
Thanks @rosa!  Having some values settable in `application.rb` and others set in `config.yaml` is a confusing developer experience.  I would think they would have parity

**Comment by rosa** [comment]
Hey @allcentury, the configuration in `solid_queue.yml` is for specific workers and dispatchers, whereas the configuration options set via `config.solid_queue` are for the Solid Queue's engine. Having these separate is a common pattern in Rails. For example, [Active Storage's engine configuration options](https://github.com/rails/rails/blob/f481353150c100dbd944d5aa84f2480264cd723c/activestorage/lib/active_storage/engine.rb#L28-L132) vs. Active Storage's [specific storage service configuration](https://edgeguides.rubyonrails.org/active_storage_overview.html#setup). I'll make this clearer in the README.
