### ISSUE TITLE
The program executes two sets, is it normal?

### ISSUE THREAD

**Issue by davidpan** [basecamp/solid_queue#109]
<img width="444" alt="image" src="https://github.com/basecamp/solid_queue/assets/12668/8d46807f-32b1-4f46-97ec-c5af781b219b">

Should only one group be started as configured?
A supervisor, a dispatcher, and a worker.

If only one group is needed, is it possible to use the kill command and just stop it?

solid_queue.yml file:
```ruby
default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      concurrency_maintenance_interval: 300
  workers:   
    - queues: "chrome_single"
      threads: 1
      processes: 1
      polling_interval: 1


development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
```

**Comment by rosa** [comment]
@davidpan, yes, you should get only 3 processes, as you said: one supervisor, one worker and one dispatcher, with that configuration. This suggests it's related to https://github.com/basecamp/solid_queue/issues/108, and your processes aren't being deregistered properly. Can you check if the processes with these pids are, in fact, running at all?

**Comment by rosa** [comment]
Closing this one in favour of #108.
