### ISSUE TITLE
SolidQueue::ReadyExecution error

### ISSUE THREAD

**Issue by rctneil** [basecamp/solid_queue#130]
Hi,

When running Solid Queue with all default config I get:

`/gems/solid_queue-0.1.2/lib/solid_queue/worker.rb:35:in `block in poll': uninitialized constant SolidQueue::ReadyExecution (NameError)
21:27:46 jobs.1   |
21:27:46 jobs.1   |           SolidQueue::ReadyExecution.claim(queues, pool.idle_threads, process.id)
21:27:46 jobs.1   |                     ^^^^^^^^^^^^^^^^
21:27:46 jobs.1   | Did you mean?  SolidQueue::FailedExecution`

Any suggestions?

**Comment by namolnad** [comment]
I just went through this yesterday. I think this generally happens on code reloads. You'll need to update to `v0.2.0` (for which you'll need to point to github vs rubygems: #129). Fix was here: #82

**Comment by rctneil** [comment]
> I just went through this yesterday. I think this generally happens on code reloads. You'll need to update to `v0.2.0` (for which you'll need to point to github vs rubygems: #129). Fix was here: #82

Awesome!  Thanks. I will for sure give this a try tomorrow.

**Comment by rosa** [comment]
Oops, so sorry! Not publishing that to RubyGems was an oversight (I was sure I had published it 🤦‍♀️ ). Since we target `main` in our apps, I didn't notice. I'll publish it ASAP.

**Comment by rosa** [comment]
[Done](https://rubygems.org/gems/solid_queue/versions/0.2.0)!
