### ISSUE TITLE
Thread.abort_on_exception = true is causing worker to be restarted even when it's handled in job

### ISSUE THREAD

**Issue by wheee** [basecamp/solid_queue#131]
So I'm not sure what the intended behaviour is but I think what I'm seeing is very odd.

If you have a simple job like so:

```
module Contracts
  class UpdateDetailsJob < ApplicationJob
    def perform
      t = Thread.new do
        sleep 2
        raise "error!"
      end
      t.abort_on_exception = true
      t.join
    rescue => ex
      puts "Error caught! - #{ex.message}"
    end
  end
end
```

I see the following happen:
```
07:35:51 solid_queue.1      | #<Thread:0x000000012f5354c8 /.../contracts/update_details_job.rb:10 run> terminated with exception (report_on_exception is true):
07:35:51 solid_queue.1      | /.../contracts/update_details_job.rb:12:in `block in perform': error! (RuntimeError)
07:35:51 solid_queue.1      | Error caught! - error!
07:35:51 solid_queue.1      | /.../contracts/update_details_job.rb:12:in `block in perform': error! (RuntimeError)
07:35:51 solid_queue.1      | [SolidQueue] Restarting fork[62533] (status: 1)
07:35:51 solid_queue.1      | [SolidQueue] Starting Worker(pid=62588, hostname=local, metadata={:polling_interval=>0.1, :queues=>"contracts", :thread_pool_size=>5})
```

Specifically the part about Restarting the fork and the worker immediately after.

Given that I'm handling the exception (and indeed it's outputting the "Error caught"), why is ithe worker thread getting restarted?  If that worker is handling multiple threads of work for other jobs, that's not very desirable.

Should also add, if you keep t.abort_on_exception = false then there's no restarting of the worker.

**Comment by rosa** [comment]
Hmmm... I think this happens because [the exception is re-raised in the main thread](https://ruby-doc.org/core-2.5.1/Thread.html#method-i-abort_on_exception-3D), which is the worker 🤔 

For example, see this code: 

```ruby
# test.rb

def run_thread_that_errors
  begin
    t = Thread.new do
      sleep 2
      raise "error!"
    end

    t.abort_on_exception = true
    t.join

  rescue => ex
    puts "Error caught! - #{ex.message}"
  end
end

Thread.new do
  run_thread_that_errors
end.join

puts "never reached"
```

```
$ ruby test.rb
#<Thread:0x0000000100bcda30 test.rb:3 run> terminated with exception (report_on_exception is true):
test.rb:5:in `block in run_thread_that_errors': error! (RuntimeError)
Error caught! - error!
test.rb:5:in `block in run_thread_that_errors': error! (RuntimeError)

$ echo $?
1
```

**Comment by rosa** [comment]
> So I wonder what the full implications are here... does that mean, don't set abort_on_exception = true?

Yes, or... maybe handle the exception that you know might happen within the inner thread itself? 🤔
