### ISSUE TITLE
Error when running Solid Queue's supervisor together with Puma

### ISSUE THREAD

**Issue by elliotlarson** [basecamp/solid_queue#136]
When I start up my rails server in development mode after having added the `plugin :solid_queue` line to my `config/puma.rb` file I get the following errors in the output when running Puma:

```log
objc[56839]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[56839]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

This doesn't appear to interfere with Puma serving local web requests, but if I kick off a background job it does not get processed.  However, if I remove the plugin config line from the Puma file and then run Solid Queue as a separate process, the Puma error goes away when starting the server and Solid Queue picks up background jobs and processes them correctly.

My local dev environment: M2 MacBook running Ventura.

**Comment by iamradioactive** [comment]
@elliotlarson, The root cause doesn't appear to be related to this gem. 

Reference: https://github.com/rails/rails/issues/38560

**Comment by elliotlarson** [comment]
@iamradioactive Ah, thank you.  That solved the problem.
