### ISSUE TITLE
Does it scale horizontally?

### ISSUE THREAD

**Issue by collimarco** [basecamp/solid_queue#138]
I am used to Sidekiq where I usually have 1 process with N threads and then I scale horizontally (e.g. I use many Kubernetes pods, each one with a Sidekiq process).

I see that Solid Queue is more like Puma, and it supports multiple threads and multiple forked processes using the config file.

Is it correct / safe to scale Solid Queue horizontally? i.e. run `bundle exec rake solid_queue:start` on multiple machines at the same time in production

Or Solid Queue supports only vertical scaling on a single machine?

**Comment by rosa** [comment]
> Is it correct / safe to scale Solid Queue horizontally? i.e. run bundle exec rake solid_queue:start on multiple machines at the same time in production

Hey @collimarco! Definitely correct and safe, in fact this is how we run it for HEY. I've got pending to write a post detailing our Solid Queue setup, with things like this but also covering other aspects such as monitoring and alerts. I just haven't had the time, but hopefully soon!

**Comment by matteeyah** [comment]
Until the blog post comes, here's how we're monitoring jobs (we're also using SolidQueue in production):

1. Running jobs
    ```sql
    SELECT "solid_queue_jobs"."active_job_id", "solid_queue_jobs"."queue_name", "solid_queue_jobs"."class_name", "solid_queue_jobs"."arguments"::JSON->'arguments' AS "arguments", "solid_queue_jobs"."scheduled_at" FROM "solid_queue_claimed_executions" LEFT JOIN "solid_queue_jobs" ON "solid_queue_claimed_executions"."job_id" = "solid_queue_jobs"."id"
    ```
2. Queued jobs
    ```sql
    SELECT "solid_queue_jobs"."active_job_id", "solid_queue_jobs"."queue_name", "solid_queue_jobs"."class_name", "solid_queue_jobs"."arguments"::JSON->'arguments' AS "arguments", "solid_queue_jobs"."scheduled_at" FROM "solid_queue_ready_executions" LEFT JOIN "solid_queue_jobs" ON "solid_queue_ready_executions"."job_id" = "solid_queue_jobs"."id"
    ```
3. Scheduled jobs
    ```sql
    SELECT  "solid_queue_jobs"."active_job_id", "solid_queue_jobs"."queue_name", "solid_queue_jobs"."class_name", "solid_queue_jobs"."arguments"::JSON->'arguments' AS "arguments", "solid_queue_scheduled_executions"."queue_name", "solid_queue_scheduled_executions"."scheduled_at" FROM "solid_queue_scheduled_executions" LEFT JOIN "solid_queue_jobs" ON "solid_queue_scheduled_executions"."job_id" = "solid_queue_jobs"."id"
    ```
4. Failed jobs
    ```sql
    SELECT "solid_queue_jobs"."active_job_id", "solid_queue_jobs"."queue_name", "solid_queue_jobs"."class_name", "solid_queue_jobs"."arguments"::JSON->'arguments' AS "arguments", "solid_queue_jobs"."scheduled_at", "solid_queue_failed_executions"."created_at", "solid_queue_failed_executions"."error" FROM "solid_queue_failed_executions" LEFT JOIN "solid_queue_jobs" ON "solid_queue_failed_executions"."job_id" = "solid_queue_jobs"."id"
    ```
    
The results of these queries are displayed as tables (inside of Blazer). Blazer also supports alerting on any of these - e.g. if there's a growing number of jobs in the queued jobs table.

Retrying is done manually through the Rails console.
