### ISSUE TITLE
Does `solid_queue` depend on the whole Rails stack?

### ISSUE THREAD

**Issue by nimmolo** [basecamp/solid_queue#156]
Hi @rosa - we'd love to try out `solid_queue` in production, but our app does not need to load ActiveStorage, ActionText or ActionMailbox. I think it's pretty common for people to just use some Rails gems.

Would you accept a simple PR #158 adjusting the `solid_queue.gemspec` so it doesn't require all of `rails` as a dependency? Including just `railties` and necessary gems is how they do it [in the gemspec](https://github.com/rails/solid_cache/blob/main/solid_cache.gemspec) for `solid_cache` too.

`solid_queue` seems to only need part of the stack. :
```ruby
# solid_queue/bin/rails

require "rails"
# Pick the frameworks you want:
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
# require "active_storage/engine"
require "action_controller/railtie"
# require "action_mailer/railtie"
require "action_view/railtie"
# require "action_cable/engine"
require "rails/test_unit/railtie"
require "rails/engine/commands"
```

**Comment by jeremy** [comment]
Continued in #158
