### ISSUE TITLE
In Development

### ISSUE THREAD

**Issue by rctneil** [basecamp/solid_queue#160]
Hi,

I've added a job in development and I have `jobs: bundle exec rake solid_queue:start` in my Procfile.dev but it doesn't run it?

What must I be doing wrong?

**Comment by rosa** [comment]
Does it work when you run it manually? With 
```
bundle exec rake solid_queue:start
```

**Comment by wrmk** [comment]
both variants work for me
ruby 3.3.0
rails 7.1.3
solid_queue 0.2.2
