### ISSUE TITLE
starting with bin/jobs or rake solid_queue:start does not start processing the queue

### ISSUE THREAD

**Issue by santy18** [basecamp/solid_queue#454]
The queue gets processed with puma whe i run `rails s`, but it does not if I start it separately. When I run `bundle exec rake solid_queue:start --trace` it stays stuck in

** Invoke solid_queue:start (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute solid_queue:start

any idea what I am doing wrong?

**Comment by santy18** [comment]
added these two to the development.rb

  config.active_job.queue_adapter = :solid_queue
  config.solid_queue.connects_to = { database: { writing: :queue } }

**Comment by rosa** [comment]
Is it really not executing jobs or aren't you seeing any logs? https://github.com/rails/solid_queue/issues/423

**Comment by santy18** [comment]
@rosa I am going to add it but... when I look at the solid_queue_processes table, there is no value in the  "finished_at" column.

alsooo, if I add a binding.pry inside of it, it does not get hit with either command

**Comment by rosa** [comment]
Hmm... strange indeed. Could you copy your `queue.yml` configuration as well? It's really weird jobs get processed when started via Puma vs. individually, since it's the same thing in the end.

**Comment by santy18** [comment]
@rosa So, it was that...but I could have sworn that I had 2 jobs that did not get finished while I was trying this out. any way, thank you for the fast reply! Thank you!
