### ISSUE TITLE
Document how to retry jobs

### ISSUE THREAD

**Issue by morgoth** [basecamp/solid_queue#66]
To retry a job, one has to configure it by hand, in example by adding `retry_on` with some logic.
I believe it is very similar to GoodJob retries, where it's documented on https://github.com/bensheldon/good_job/tree/50199f9bfcaca1c23ae7373efe781c1862dcc0cb#retries

Also a note how to report an error on retry would be very useful. Currently only the final error (the one that no longer is retried) is reported via `on_thread_error`.

I could try to prepare PR, but I'm very curious how to do it in your production apps

**Comment by rosa** [comment]
Great point, @morgoth! I'll document this in the README, it was an oversight of mine, not including this.
