### ISSUE TITLE
Missing GUI

### ISSUE THREAD

**Issue by jmarsh24** [basecamp/solid_queue#70]
I don't see any reference to access a GUI interface for this library. Is this just missing from the documentation? I also skimmed through the codebase and didn't see anything regarding a GUI user interface. Perhaps if it's still in the works, it would be great to still create a GUI interface section in the readme and state this it's a work in progress?

**Comment by brunoprietog** [comment]
https://twitter.com/dhh/status/1736882022831079738

**Comment by rosa** [comment]
Thanks @brunoprietog! 🙏 

@jmarsh24, basically what Bruno posted: we're going to open-source a separate gem that will work with Solid Queue but also with other adapters like Resque. We hope to do it early next year 😊
