### ISSUE TITLE
Should the dispatcher run on only one server?

### ISSUE THREAD

**Issue by brenogazzola** [basecamp/solid_queue#85]
I was trying to figure out if having a dispatcher process running on multiple servers would be a problem, and I noticed on the rake tasks there are there are two other tasks (`work`and `dispatch`) that boot solid_queue with only those of two processes.

So my question is: If I have multiple servers, am I supposed to use `solid_queue:start` on all of them, or do I use `solid_queue:start` on a single one and `solid_queue:work` on the rest?

**Comment by rosa** [comment]
Great question! Having multiple dispatcher processes running on multiple servers is totally fine. We do that for HEY. The only reason to have those other rake tasks was for convenience, as in HEY, we have VMs dedicated to workers and VMs dedicated to the dispatcher, but it doesn't need to be that way.

**Comment by brenogazzola** [comment]
Great, thanks!
